---
title: "Lower-Bounded Likelihoods and Links"
author: "Maximilian Scholz"
date: "5/02/2022"
output:
  bookdown::html_document2: default
---

# Setup
```{r, setup, message=FALSE}
library(brms)
library(bayesim)
library(bayesfam)
library(dplyr)
library(purrr)
library(patchwork)
library(ggplot2)
library(ggthemes)
set.seed(1235813)
library(scico)

figure_path = "~/Documents/dr/ms_calibration/lower-bounded/figures/"

plot_dist <- function(dist, bounds, pars, prefix = "d", parnames = NULL,
                      package = NULL, user_theme = ggthemes::theme_tufte, ...) {
  `%>%` <- dplyr::`%>%`
  pos <- -1
  if (!is.null(package)) {
    pos <- asNamespace(package)
  }
  ddist <- get(paste0(prefix, dist), pos = pos, mode = "function")
  df <- data.frame(x = seq(bounds[1], bounds[2], 0.001))
  if (!is.null(parnames)) {
    parnames <- paste0(parnames, " = ")
  }
  cnames <- rep(NA, length(pars))
  for (i in seq_along(pars)) {
    tmp <- do.call(ddist, c(list(df$x), pars[[i]], list(...)))
    cnames[i] <- paste0("$", parnames, pars[[i]], "$", collapse = ", ")
    df[paste0(parnames, pars[[i]], collapse = ", ")] <- tmp
  }
  df <- df %>%
    tidyr::gather("pars", "dens", -x) %>%
    dplyr::mutate(pars = factor(pars, unique(pars)))
  gg <- ggplot2::ggplot(df, ggplot2::aes(x, dens, color = pars)) +
    user_theme() +
    ggplot2::geom_line(size = 1) +
    scico::scale_colour_scico_d(palette = "batlow",end = 0.8, labels = unname(latex2exp::TeX(cnames))) +
    ggplot2::labs(x = "x", y = "", color = "") +
    ggplot2::theme(
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      axis.line.y = ggplot2::element_blank(),
      legend.position = "bottom",
      legend.text = ggplot2::element_text(size = 10)
    )
  if (prefix == "p") {
    gg <- gg +
      ggplot2::scale_y_continuous(breaks = c(0, 0.5, 1)) +
      ggplot2::theme(
        axis.ticks.y = ggplot2::element_line(),
        axis.text.y = ggplot2::element_text(),
        axis.line.y = ggplot2::element_line()
      )
  } else if (prefix == "q") {
    gg <- gg +
      ggplot2::scale_y_continuous() +
      ggplot2::theme(
        axis.ticks.y = ggplot2::element_line(),
        axis.text.y = ggplot2::element_text(),
        axis.line.y = ggplot2::element_line()
      )
  }
  return(gg)
}
```

# Distribution Shapes

## Gamma

```{r}
p1 <- plot_dist(
  dist = "gamma_mean",
  bounds = c(0.00001, 20),
  parnames = c("mu", "a"),
  package = "bayesfam",
  pars = list(
    c(1, 1),
    c(10, 10),
    c(10, 40)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Gamma") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())

p1
```

## Weibull

```{r}
p2 <- plot_dist(
  dist = "weibull_median",
  bounds = c(0.00001, 20),
  parnames = c("mu", "k"),
  package = "bayesfam",
  pars = list(
    c(1, 1),
    c(10, 4),
    c(10, 8)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Weibull") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())
p2
```

## Lognormal

```{r}
p3 <- plot_dist(
  dist = "lognormal",
  bounds = c(0.00001, 20),
  parnames = c("mu", "sigma"),
  package = "bayesfam",
  pars = list(
    c(log(1), 1),
    c(log(10), 0.35),
    c(log(10), 0.15)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Log-Normal") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())
p3
```

## Softplusnormal

```{r}
p4 <- plot_dist(
  dist = "softplusnormal",
  bounds = c(0.00001, 20),
  parnames = c("mu", "sigma"),
  package = "bayesfam",
  pars = list(
    c(softplus(1), 2),
    c(softplus(10), 4),
    c(softplus(10), 2)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Softplus-Normal") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())
p4
```

## Frechet

```{r}
p5 <- plot_dist(
  dist = "frechet_median",
  bounds = c(0.0001, 20),
  parnames = c("mu", "nu"),
  package = "bayesfam",
  pars = list(
    c(1, 2),
    c(10, 5),
    c(10, 10)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Fréchet") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())
p5
```

## Inverse Gaussian

```{r}
p6 <- plot_dist(
  dist = "inv_gaussian",
  bounds = c(0.0001, 20),
  parnames = c("mu", "shape"),
  package = "brms",
  pars = list(
    c(1, 1),
    c(10, 10),
    c(10, 100)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Inverse Gaussian") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())
p6
```

## Beta Prime

```{r}
p7 <- plot_dist(
  dist = "betaprime",
  bounds = c(0.0001, 20),
  parnames = c("mu", "phi"),
  package = "bayesfam",
  pars = list(
    c(1, 1),
    c(10, 20),
    c(10, 50)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Beta prime") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())
p7
```

##Gompertz

```{r}
p8 <- plot_dist(
  dist = "gompertz",
  bounds = c(0.00001, 20),
  parnames = c("mu", "eta"),
  package = "bayesfam",
  pars = list(
    c(1, 0.2),
    c(10, 0.3),
    c(10, 0.6)
    ),
  user_theme = partial(theme_tufte, base_family = "")
  ) +
  ggtitle("Gompertz") +
  guides(color = "none") +
  coord_cartesian(ylim = c(0, 0.4)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "grey") +
  theme(axis.title.x = element_blank())
p8
```
## Combined

```{r, all-setup}
(((p1 + p2 + p5) / (p6 + p7 + p8) /(p3 + plot_spacer() + p4)) ) + theme(text=element_text(size=12))
ggsave(paste0(figure_path, "positive_densities.pdf"),
  width = 210, height = (297/4)*1.3, units = "mm", useDingbats = TRUE)
```

# Link Showcase

```{r, positive-links}
x <- seq(-2, 3, length.out = 500)
data <- data.frame(x = x,
                   values = c(exp(x),
                   inv_softplus(x)),
                   Fun = rep(c("Log", "Softplus"), each = 500))
                   
p1 <- ggplot(data, aes(x, values, col = factor(Fun, levels = c("Log", "Softplus")))) +
  coord_cartesian(xlim = c(-2, 3),  ylim = c(0, 3)) +
  geom_line(size = 1) +
  geom_abline(slope=1, intercept=0, color = "grey", linetype = "dashed") +
  #scale_color_manual(values = my_colors) +
  scale_color_scico_d(palette = "batlow", end = 0.8)+
  ggthemes::theme_tufte(base_family = "") +
  ggplot2::labs(x = "", y = "", color = "") +
  ggplot2::theme(
    legend.position = "bottom",
    legend.text = ggplot2::element_text(size = 12)
  ) +
  ggtitle("Lower-Bounded Response Functions")
p1


x <- seq(0.001, 3, length.out = 500)
data <- data.frame(x = x,
                   values = c(log(x),
                   softplus(x)),
                   Fun = rep(c("Log", "Softplus"), each = 500))
                   
p2 <- ggplot(data, aes(x, values, col = factor(Fun, levels = c("Log", "Softplus")))) +
  coord_cartesian(ylim = c(-3, 3),  xlim = c(0, 3)) +
  geom_line(size = 1) +
  geom_abline(slope=1, intercept=0, color = "grey", linetype = "dashed") +
  #scale_color_manual(values = my_colors) +
  scale_color_scico_d(palette = "batlow", end = 0.8)+
  ggthemes::theme_tufte(base_family = "") +
  ggplot2::labs(x = "", y = "", color = "") +
  ggplot2::theme(
    legend.position = "bottom",
    legend.text = ggplot2::element_text(size = 12)
  ) +
  ggtitle("Lower-Bounded Link Functions")
p2

p2 + p1
ggsave(paste0(figure_path, "positive_link_response_showcase.pdf"),
       width = 210, height = (297/4)*0.7, units = "mm", useDingbats = TRUE)
```
